---
title: "First Time"
date: 2021-03-30
---
title: Denise Martinez
theme: minima
author: GitHub User
email: martinezdenise410@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site. Here is some of my work. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  DeniseM1717 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
